version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

prepare_twine: &prepare_twine
  run:
    name: Install twine
    command: |
      sudo pip install --upgrade pip
      pip install --user twine


jobs:
  model_test_and_upload_test:
    <<: *defaults
    working_directory: ~/project/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      # - *prepare_twine
      - run:
          name: Test model package
          command: |
            tox
      - run:
          name: Upload to Gemfury or TestPYPI
          command: |
            tox -e publish_test_model

  test_app:
    <<: *defaults
    working_directory: ~/project/translator-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Testing translator app
          # runs test by posting payload to api
          command: |
            tox -v

  deploy_app_to_heroku:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Heroku
          command: |
            git subtree push --prefix=translator-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_2.git master
            

  test_and_upload_regression_model:
    <<: *defaults
    working_directory: ~/project/model_package
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - *prepare_twine
      - run:
          name: Publish model to PyPI
          command: |
            tox -e publish_model


tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  Deploy:
    jobs:
      - model_test_and_upload_test:
          filters:
            branches:
              only:
                - main
      - test_app:
          requires:
            - model_test_and_upload_test
          filters:
            branches:
              only:
                - main
      - deploy_app_to_heroku:
          requires:
            - test_app
          filters:
            branches:
              only:
                - master
      # - test_and_upload_regression_model:
      #     filters:
      #       branches:
      #         only:
      #           - main
